Activities to complete:
 Data cleansing involves removing unnecessary columns.
 Giving the columns new names.
 Eliminating redundant entries.
 sanitizing specific columns.
 Eliminate the dataset's NaN values.
 Look for a few more changes if necessary

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split


In [ ]:
df=pd.read_csv('/content/HR Data.csv')
df.head()

Age Attrition  ... YearsSinceLastPromotion  YearsWithCurrManager
0   41       Yes  ...                       0                     5
1   49        No  ...                       1                     7
2   37       Yes  ...                       0                     0
3   33        No  ...                       3                     0
4   27        No  ...                       2                     2

[5 rows x 35 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   int64 
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64 
 9   EmployeeNumber            1470 non-null   int64 
 10  EnvironmentSatisfaction   1470 non-null   int64 
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64 
 13  JobInvolvement            1470 non-null   int64 
 14  JobLevel                

Eliminating redundant entries.

In [ ]:
df.duplicated().sum()

0

In [ ]:
df=df.drop_duplicates()

Eliminate the dataset's NaN values.

In [ ]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
df=df.dropna()

In [ ]:
df['EmployeeCount'].unique()

array([1])

In [ ]:
df['StandardHours'].unique()

array([80])

In [ ]:
df['EmployeeNumber'].unique()

array([   1,    2,    4, ..., 2064, 2065, 2068])

In [ ]:
df['Over18'].unique()

array(['Y'], dtype=object)

 Data cleansing involves removing unnecessary columns.

In [ ]:
df=df.drop(['EmployeeCount', 'StandardHours', 'EmployeeNumber'],axis=1)

KeyError: "['EmployeeCount', 'StandardHours', 'EmployeeNumber'] not found in axis"

In [ ]:
df=df.drop(['Over18'],axis=1)

In [ ]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18',
       'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

 Giving the columns new names.

In [ ]:
df=df.rename(columns={'Attrition': 'IsAttrition',
    'BusinessTravel': 'Travel_Frequency',
    'DailyRate': 'Daily_Rate_USD',
    'Education': 'Education_Level',
    'EducationField': 'Field_Of_Study',
    'TotalWorkingYears': 'Total_Experience_Years',
    'YearsAtCompany': 'Tenure_Years',
    'YearsInCurrentRole': 'Current_Role_Years',
    'YearsSinceLastPromotion': 'Years_Since_Promotion',
    'YearsWithCurrManager': 'Manager_Years'})

 sanitizing specific columns

In [ ]:
df= df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

<ipython-input-22-f9824bcda59a>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df= df.applymap(lambda x: x.strip() if isinstance(x, str) else x)


In [ ]:
df.head()

Age IsAttrition   Travel_Frequency  ...  Current_Role_Years Years_Since_Promotion  Manager_Years
0   41         Yes      Travel_Rarely  ...                   4                     0              5
1   49          No  Travel_Frequently  ...                   7                     1              7
2   37         Yes      Travel_Rarely  ...                   0                     0              0
3   33          No  Travel_Frequently  ...                   7                     3              0
4   27          No      Travel_Rarely  ...                   2                     2              2

[5 rows x 31 columns]

In [ ]:
df.skew

<bound method DataFrame.skew of       Age IsAttrition   Travel_Frequency  ...  Current_Role_Years Years_Since_Promotion  Manager_Years
0      41         Yes      Travel_Rarely  ...                   4                     0              5
1      49          No  Travel_Frequently  ...                   7                     1              7
2      37         Yes      Travel_Rarely  ...                   0                     0              0
3      33          No  Travel_Frequently  ...                   7                     3              0
4      27          No      Travel_Rarely  ...                   2                     2              2
...   ...         ...                ...  ...                 ...                   ...            ...
1465   36          No  Travel_Frequently  ...                   2                     0              3
1466   39          No      Travel_Rarely  ...                   7                     1              7
1467   27          No      Travel_Rarely  ...                   2                     0              3
1468   49          No  Travel_Frequently  ...                   6                     0              8
1469   34          No      Travel_Rarely  ...                   3                     1              2

[1470 rows x 31 columns]>

In [ ]:
x=df.drop(['IsAttrition'],axis=1)
y=df['IsAttrition']

In [ ]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [ ]:
le=LabelEncoder()
df['IsAttrition']=le.fit_transform(df['IsAttrition'])
df['Travel_Frequency']=le.fit_transform(df['Travel_Frequency'])
df['Field_Of_Study']=le.fit_transform(df['Field_Of_Study'])
df['Gender']=le.fit_transform(df['Gender'])
df['Department']=le.fit_transform(df['Department'])
df['JobRole']=le.fit_transform(df['JobRole'])
df['MaritalStatus']=le.fit_transform(df['MaritalStatus'])
df['OverTime']=le.fit_transform(df['OverTime'])


In [ ]:
x.head()

Age  Travel_Frequency  Daily_Rate_USD  ...  Current_Role_Years  Years_Since_Promotion  Manager_Years
0   41                 2            1102  ...                   4                      0              5
1   49                 1             279  ...                   7                      1              7
2   37                 2            1373  ...                   0                      0              0
3   33                 1            1392  ...                   7                      3              0
4   27                 2             591  ...                   2                      2              2

[5 rows x 30 columns]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train.shape,y_train.shape

((1176, 30), (1176,))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
re=RandomForestClassifier()
re.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred=re.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred)

0.8775510204081632

In [ ]:
input=(41,2,1102,2,1,2,1,2,0,94,3,2,7,4,2,5993,19479,8,1,11,3,1,0,8,0,1,6,4,0,5)
input_array=np.asarray(input)
input_reshaped=input_array.reshape(1,-1)
predicition=re.predict(input_reshaped)
if predicition[0]==0:
  print('Employee will not leave the company')
else:
  print('Employee will leave')
